version: "3.9"
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html:cached
    environment:
      APP_ENV: dev
    working_dir: /var/www/html

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
